### ISSUE TITLE
libtiff.so.5 error (Arch Linux)

### ISSUE THREAD

**Issue by ghost** [TheDrawingCoder-Gamer/GorillaModManager#6]
I am running Arch Linux and encountered an issue when trying to run GMM.

```
./Main: /usr/lib/libtiff.so.5: no version information available (required by ./Main)
Error : [file_contents,/home/garrett/Projects/Sandbox/gorilla/Main/assets/sources.xml]
```

**Comment by TheDrawingCoder-Gamer** [comment]
libtiff seems to not really matter; it can't find sources.xml; did you delete assets?

**Comment by ghost** [comment]
I don't have the files from the last time I tried using this program, nor do I need this anymore. I will leave this closed. thank you for working on this project!
